- become: true
  gather_facts: true
  hosts: all
  name: Converge
  roles:
  - role: buluma.squid
    squid_acls:
    - classifier: src
      name: localnet
      value: 0.0.0.1-0.255.255.255
    squid_cache_dir: aufs /var/spool/squid 16000 16 256 max-size=8589934592
    squid_cache_replacement_policy: heap LFUDA
    squid_maximum_object_size_mb: 256
    squid_rules:
    - acl: to_localhost
      decision: deny
    - acl: localnet
      decision: allow
    - acl: localhost
      decision: allow
    - acl: all
      decision: deny
