---
- become: true
  gather_facts: false
  hosts: all
  name: Verify
  tasks:
  - ansible.builtin.uri:
      url: http://www.google.com/
    environment:
      http_proxy: http://localhost:3128
      https_proxy: http://localhost:3128
    name: test the proxy
